"""InkosAI AetherGit — Advanced version control for AI agent orchestration."""

from packages.aethergit.advanced import (
    AdvancedAetherGit,
    AetherGitError,
    BranchDAG,
    BranchEdge,
    BranchNode,
    BranchNotFoundError,
    CommitDiff,
    CommitNotFoundError,
    CommitStore,
    EmbeddingProvider,
    MergeAnalysis,
    MergeConflict,
    MergeConflictType,
    MergeResolution,
    MergeResolutionReport,
    MergeResolutionStrategy,
    MetricDelta,
    SearchResult,
    SearchResults,
    WorktreeError,
    WorktreeInfo,
    WorktreeNotFoundError,
    WorktreeStatus,
)

__all__ = [
    "AdvancedAetherGit",
    "AetherGitError",
    "BranchDAG",
    "BranchEdge",
    "BranchNode",
    "BranchNotFoundError",
    "CommitDiff",
    "CommitNotFoundError",
    "CommitStore",
    "EmbeddingProvider",
    "MergeAnalysis",
    "MergeConflict",
    "MergeConflictType",
    "MergeResolution",
    "MergeResolutionReport",
    "MergeResolutionStrategy",
    "MetricDelta",
    "SearchResult",
    "SearchResults",
    "WorktreeError",
    "WorktreeInfo",
    "WorktreeNotFoundError",
    "WorktreeStatus",
]
