"""One-Click Domain Creation — Instant specialised domains from natural language.

This module enables users (and Prime) to create entirely new specialised domains
with pre-configured agents, skills, workflows, and settings — from a simple
natural language description.

Core flow:

1. **generate_domain_blueprint()** — Parse a natural language description and
   auto-generate a complete domain blueprint with:
   - Domain name, ID, and description
   - 4-8 specialised agents with roles, goals, and backstories
   - Relevant skills (new or reused from existing registry)
   - 2-3 starter crews/workflows
   - Domain-specific configuration and constraints

2. **create_domain_from_description()** — Orchestrate the full creation pipeline:
   blueprint generation -> validation -> Proposal submission -> (await approval)
   -> domain registration.

3. **register_domain()** — Save the new domain to the DomainRegistry after
   proposal approval.

Safety guarantees:

- All new domains go through the Proposal approval workflow
- Duplicate domain names are prevented
- Generated content is validated for completeness and safety
- Both fully-automatic and human-guided creation modes are supported
- All creation events are logged to the Tape

Architecture::

    DomainCreationEngine
    +-- create_domain_from_description()  -- Full pipeline
    +-- generate_domain_blueprint()       -- NL -> DomainBlueprint
    +-- register_domain()                 -- Blueprint -> DomainRegistry
    +-- validate_blueprint()              -- Safety and completeness checks
    +-- list_domains()                    -- List all available domains
    +-- get_domain()                      -- Retrieve a single domain
    +-- get_blueprint()                   -- Retrieve a stored blueprint

Usage::

    engine = DomainCreationEngine(
        tape_service=tape_svc,
        introspector=introspector,
        proposal_engine=proposal_engine,
    )

    # Generate a blueprint from a description
    blueprint = await engine.generate_domain_blueprint(
        description="Create a Legal Research Domain for contract analysis "
                    "and compliance checking",
    )

    # Full creation (generates blueprint, validates, creates proposal)
    result = await engine.create_domain_from_description(
        description="Create a Legal Research Domain for contract analysis "
                    "and compliance checking",
        created_by="human-001",
    )
    # result.proposal.status == "pending_approval"

    # After human approval of the proposal, register the domain
    domain = await engine.register_domain(blueprint.id)
"""

import contextlib
import re
from datetime import UTC, datetime
from enum import StrEnum
from typing import ClassVar
from uuid import UUID, uuid4

from pydantic import BaseModel, Field

from packages.aethergit.advanced import AdvancedAetherGit
from packages.core.models import AetherCommit
from packages.folder_tree import FolderTreeService
from packages.prime.introspection import (
    AgentDescriptor,
    DomainDescriptor,
    DomainRegistry,
    PrimeIntrospector,
    SkillDescriptor,
)
from packages.prime.proposals import (
    ModificationType,
    ProposalEngine,
    ProposalStatus,
    RiskLevel,
)
from packages.tape.service import TapeService

# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------


class CreationMode(StrEnum):
    """How the domain was created."""

    AUTOMATIC = "automatic"  # Fully generated by Prime
    HUMAN_GUIDED = "human_guided"  # Human provided the description
    HYBRID = "hybrid"  # Human described, Prime refined


class DomainStatus(StrEnum):
    """Lifecycle status of a domain."""

    DRAFT = "draft"  # Blueprint generated, not yet proposed
    PROPOSED = "proposed"  # Proposal submitted, awaiting approval
    ACTIVE = "active"  # Approved and registered
    DEPRECATED = "deprecated"  # Domain no longer in use
    ARCHIVED = "archived"  # Permanently archived


class AgentRole(StrEnum):
    """Roles that an agent can play within a domain."""

    COORDINATOR = "coordinator"  # Orchestrates other agents
    ANALYST = "analyst"  # Analyses data and produces insights
    EXECUTOR = "executor"  # Carries out actions and tasks
    REVIEWER = "reviewer"  # Reviews outputs for quality and compliance
    RESEARCHER = "researcher"  # Gathers information and knowledge
    SPECIALIST = "specialist"  # Deep expertise in a narrow area
    MONITOR = "monitor"  # Watches system health and metrics
    COMMUNICATOR = "communicator"  # Interfaces with humans or other domains


class WorkflowType(StrEnum):
    """Types of starter workflows for a domain."""

    SEQUENTIAL = "sequential"  # Step-by-step pipeline
    PARALLEL = "parallel"  # Concurrent execution
    ITERATIVE = "iterative"  # Feedback loop
    PIPELINE = "pipeline"  # Data processing chain
    DEBATE = "debate"  # Multi-agent discussion
    REVIEW = "review"  # Draft-review-approve cycle


# ---------------------------------------------------------------------------
# Data models
# ---------------------------------------------------------------------------


class AgentBlueprint(BaseModel):
    """Blueprint for an agent to be created within a domain."""

    agent_id: str
    name: str
    role: AgentRole = AgentRole.SPECIALIST
    goal: str = ""
    backstory: str = ""
    capabilities: list[str] = []
    tools: list[str] = []


class SkillBlueprint(BaseModel):
    """Blueprint for a skill (new or reused) within a domain."""

    skill_id: str
    name: str
    description: str = ""
    version: str = "0.1.0"
    is_reused: bool = False  # True if the skill already exists in the registry
    source_domain: str | None = None  # Domain the reused skill came from


class WorkflowBlueprint(BaseModel):
    """Blueprint for a starter workflow/crew within a domain."""

    workflow_id: str
    name: str
    workflow_type: WorkflowType = WorkflowType.SEQUENTIAL
    description: str = ""
    agent_ids: list[str] = []  # Agents involved in this workflow
    steps: list[str] = []  # Ordered steps or phases


class DomainConfig(BaseModel):
    """Domain-specific configuration and constraints."""

    max_agents: int = 10
    max_concurrent_tasks: int = 5
    requires_human_approval: bool = True
    data_retention_days: int = 90
    priority_level: str = "normal"  # "low", "normal", "high", "critical"
    custom_settings: dict[str, object] = {}


class DomainBlueprint(BaseModel):
    """Complete blueprint for a new domain.

    Generated from a natural language description, validated for
    completeness, and submitted as a Proposal for approval.
    """

    id: UUID = Field(default_factory=uuid4)
    domain_name: str
    domain_id: str = ""  # Slug-style identifier (auto-generated)
    description: str = ""
    source_description: str = ""  # Original NL description
    agents: list[AgentBlueprint] = []
    skills: list[SkillBlueprint] = []
    workflows: list[WorkflowBlueprint] = []
    config: DomainConfig = Field(default_factory=DomainConfig)
    creation_mode: CreationMode = CreationMode.HUMAN_GUIDED
    status: DomainStatus = DomainStatus.DRAFT
    proposal_id: UUID | None = None
    created_by: str = "prime"
    created_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    validation_errors: list[str] = []
    validation_warnings: list[str] = []


class DomainCreationResult(BaseModel):
    """Result of a domain creation attempt."""

    blueprint: DomainBlueprint
    proposal_id: UUID | None = None
    registered: bool = False
    domain: DomainDescriptor | None = None
    message: str = ""


# ---------------------------------------------------------------------------
# Exceptions
# ---------------------------------------------------------------------------


class DomainCreationError(Exception):
    """Base exception for domain creation operations."""


class DuplicateDomainError(DomainCreationError):
    """Raised when a domain with the same name or ID already exists."""


class BlueprintValidationError(DomainCreationError):
    """Raised when a blueprint fails validation."""


class BlueprintNotFoundError(DomainCreationError):
    """Raised when a requested blueprint does not exist."""


class DomainNotApprovedError(DomainCreationError):
    """Raised when trying to register a domain whose proposal is not approved."""


# ---------------------------------------------------------------------------
# Blueprint Store (in-memory; will be Postgres-backed later)
# ---------------------------------------------------------------------------


class BlueprintStore:
    """In-memory store for domain blueprints."""

    def __init__(self) -> None:
        self._blueprints: dict[UUID, DomainBlueprint] = {}

    def add(self, blueprint: DomainBlueprint) -> None:
        self._blueprints[blueprint.id] = blueprint

    def get(self, blueprint_id: UUID) -> DomainBlueprint | None:
        return self._blueprints.get(blueprint_id)

    def get_by_domain_id(self, domain_id: str) -> DomainBlueprint | None:
        for bp in self._blueprints.values():
            if bp.domain_id == domain_id:
                return bp
        return None

    def list_all(self) -> list[DomainBlueprint]:
        return list(self._blueprints.values())

    def update(self, blueprint: DomainBlueprint) -> None:
        if blueprint.id not in self._blueprints:
            raise BlueprintNotFoundError(
                f"Blueprint {blueprint.id} not found"
            )
        self._blueprints[blueprint.id] = blueprint

    def remove(self, blueprint_id: UUID) -> None:
        with contextlib.suppress(KeyError):
            del self._blueprints[blueprint_id]


# ---------------------------------------------------------------------------
# BlueprintGenerator — transforms NL descriptions into DomainBlueprints
# ---------------------------------------------------------------------------


class BlueprintGenerator:
    """Generates domain blueprints from natural language descriptions.

    Uses heuristic template-based generation to produce complete domain
    blueprints. The generator analyses the description for domain keywords,
    task patterns, and expertise areas to produce appropriate agents,
    skills, and workflows.

    In production, this would call an LLM. For now, it uses structured
    heuristics that produce reasonable defaults.
    """

    # Domain archetype templates — used when the description matches
    # a known pattern.  Each archetype defines agent roles, skill areas,
    # and workflow types that are appropriate for the domain.
    _ARCHETYPES: ClassVar[dict[str, dict[str, object]]] = {
        "research": {
            "agents": [
                (AgentRole.COORDINATOR, "Research Lead", "Orchestrates research activities and synthesises findings"),
                (AgentRole.RESEARCHER, "Primary Researcher", "Conducts deep research on core topics"),
                (AgentRole.ANALYST, "Data Analyst", "Analyses and interprets research data"),
                (AgentRole.REVIEWER, "Peer Reviewer", "Reviews research outputs for quality and accuracy"),
                (AgentRole.COMMUNICATOR, "Knowledge Publisher", "Prepares and publishes research findings"),
            ],
            "skills": ["literature_review", "data_analysis", "citation_tracking", "report_writing"],
            "workflows": [(WorkflowType.SEQUENTIAL, "Research Pipeline", "Plan -> Research -> Analyse -> Review -> Publish")],
        },
        "legal": {
            "agents": [
                (AgentRole.COORDINATOR, "Legal Operations Lead", "Manages legal workflows and resource allocation"),
                (AgentRole.SPECIALIST, "Contract Analyst", "Analyses contract terms and identifies risks"),
                (AgentRole.REVIEWER, "Compliance Checker", "Verifies compliance with regulations and policies"),
                (AgentRole.RESEARCHER, "Legal Researcher", "Researches case law, precedents, and regulations"),
                (AgentRole.ANALYST, "Risk Assessor", "Evaluates legal risks and produces risk reports"),
                (AgentRole.COMMUNICATOR, "Client Liaison", "Communicates findings and recommendations to stakeholders"),
            ],
            "skills": ["contract_analysis", "compliance_checking", "legal_research", "risk_assessment", "document_review"],
            "workflows": [
                (WorkflowType.REVIEW, "Contract Review Cycle", "Draft -> Review -> Flag -> Revise -> Approve"),
                (WorkflowType.SEQUENTIAL, "Compliance Audit", "Scope -> Check -> Report -> Remediate"),
            ],
        },
        "engineering": {
            "agents": [
                (AgentRole.COORDINATOR, "Engineering Lead", "Coordinates engineering tasks and priorities"),
                (AgentRole.EXECUTOR, "Developer", "Implements features and fixes"),
                (AgentRole.REVIEWER, "Code Reviewer", "Reviews code for quality, security, and style"),
                (AgentRole.MONITOR, "SRE Watch", "Monitors system health and responds to incidents"),
                (AgentRole.ANALYST, "Performance Analyst", "Analyses system performance and identifies bottlenecks"),
                (AgentRole.SPECIALIST, "Security Specialist", "Handles security audits and vulnerability assessments"),
            ],
            "skills": ["code_review", "testing", "deployment", "monitoring", "security_audit", "performance_analysis"],
            "workflows": [
                (WorkflowType.PIPELINE, "CI/CD Pipeline", "Build -> Test -> Review -> Deploy"),
                (WorkflowType.ITERATIVE, "Incident Response", "Detect -> Triage -> Fix -> Review -> Postmortem"),
            ],
        },
        "finance": {
            "agents": [
                (AgentRole.COORDINATOR, "Finance Operations Lead", "Manages financial workflows and reporting"),
                (AgentRole.ANALYST, "Financial Analyst", "Analyses financial data and market trends"),
                (AgentRole.SPECIALIST, "Risk Manager", "Evaluates financial risks and exposure"),
                (AgentRole.REVIEWER, "Audit Reviewer", "Conducts financial audits and compliance checks"),
                (AgentRole.RESEARCHER, "Market Researcher", "Researches market conditions and opportunities"),
            ],
            "skills": ["financial_analysis", "risk_modeling", "audit_trail", "market_research", "forecasting"],
            "workflows": [
                (WorkflowType.SEQUENTIAL, "Financial Reporting", "Collect -> Analyse -> Review -> Publish"),
                (WorkflowType.DEBATE, "Investment Committee", "Propose -> Debate -> Vote -> Execute"),
            ],
        },
        "healthcare": {
            "agents": [
                (AgentRole.COORDINATOR, "Care Coordinator", "Coordinates patient care workflows"),
                (AgentRole.SPECIALIST, "Diagnostic Specialist", "Assists with diagnosis and treatment planning"),
                (AgentRole.REVIEWER, "Quality Assurance", "Reviews care plans for safety and compliance"),
                (AgentRole.MONITOR, "Patient Monitor", "Monitors patient data and alerts on anomalies"),
                (AgentRole.RESEARCHER, "Medical Researcher", "Researches treatments, drug interactions, and best practices"),
            ],
            "skills": ["diagnosis_support", "drug_interaction_check", "care_plan_review", "patient_monitoring", "medical_research"],
            "workflows": [
                (WorkflowType.REVIEW, "Treatment Planning", "Assess -> Plan -> Review -> Approve -> Execute"),
                (WorkflowType.ITERATIVE, "Patient Monitoring", "Monitor -> Alert -> Intervene -> Reassess"),
            ],
        },
    }

    # Keyword mapping — which description keywords map to which archetype
    _KEYWORD_MAP: ClassVar[dict[str, str]] = {
        "legal": "legal", "contract": "legal", "compliance": "legal",
        "regulation": "legal", "law": "legal", "attorney": "legal",
        "research": "research", "study": "research", "academic": "research",
        "paper": "research", "literature": "research", "publish": "research",
        "engineering": "engineering", "software": "engineering", "code": "engineering",
        "deploy": "engineering", "devops": "engineering", "sre": "engineering",
        "security": "engineering", "build": "engineering", "test": "engineering",
        "finance": "finance", "trading": "finance", "investment": "finance",
        "market": "finance", "risk": "finance", "audit": "finance",
        "portfolio": "finance", "forecast": "finance",
        "healthcare": "healthcare", "medical": "healthcare", "patient": "healthcare",
        "diagnosis": "healthcare", "treatment": "healthcare", "drug": "healthcare",
        "clinical": "healthcare", "care": "healthcare",
    }

    def generate(
        self,
        description: str,
        domain_name: str | None = None,
        creation_mode: CreationMode = CreationMode.HUMAN_GUIDED,
        existing_skills: list[SkillDescriptor] | None = None,
    ) -> DomainBlueprint:
        """Generate a domain blueprint from a natural language description.

        Args:
            description: Natural language description of the desired domain.
            domain_name: Optional explicit domain name; auto-generated if not provided.
            creation_mode: How the domain was created.
            existing_skills: Skills already in the registry for potential reuse.

        Returns:
            A DomainBlueprint ready for validation and proposal submission.
        """
        desc_lower = description.lower()
        archetype_key = self._detect_archetype(desc_lower)

        # Generate domain name and ID
        name = domain_name or self._generate_name(description, archetype_key)
        domain_id = self._generate_id(name)

        # Generate domain description
        domain_desc = self._generate_description(description, archetype_key)

        # Generate agents
        agents = self._generate_agents(desc_lower, archetype_key, domain_id)

        # Generate skills
        skills = self._generate_skills(
            desc_lower, archetype_key, domain_id, existing_skills or [],
        )

        # Generate workflows
        workflows = self._generate_workflows(
            desc_lower, archetype_key, domain_id, agents,
        )

        # Generate config
        config = self._generate_config(desc_lower, archetype_key)

        return DomainBlueprint(
            domain_name=name,
            domain_id=domain_id,
            description=domain_desc,
            source_description=description,
            agents=agents,
            skills=skills,
            workflows=workflows,
            config=config,
            creation_mode=creation_mode,
        )

    def _detect_archetype(self, description_lower: str) -> str:
        """Detect the best matching archetype from the description keywords."""
        scores: dict[str, int] = {}
        for keyword, archetype in self._KEYWORD_MAP.items():
            if keyword in description_lower:
                scores[archetype] = scores.get(archetype, 0) + 1
        if scores:
            return str(max(scores, key=lambda k: scores[k]))
        return "research"  # Default fallback

    def _generate_name(
        self, description: str, archetype_key: str,
    ) -> str:
        """Generate a human-readable domain name from the description."""
        # Try to extract a meaningful noun phrase from the description
        # Simple heuristic: take key words and capitalise
        archetype_names = {
            "legal": "Legal Operations",
            "research": "Research",
            "engineering": "Engineering",
            "finance": "Financial Operations",
            "healthcare": "Healthcare",
        }

        # Look for quoted or capitalized phrases
        quoted = re.findall(r'"([^"]+)"', description)
        if quoted:
            return str(quoted[0])

        # Look for "X Domain" or "X domain" pattern
        domain_match = re.search(
            r"(\w+(?:\s+\w+)?)\s+[Dd]omain", description,
        )
        if domain_match:
            return f"{domain_match.group(1).strip()} Domain"

        # Use archetype name + "Domain"
        base = archetype_names.get(archetype_key, "Custom")
        return f"{base} Domain"

    def _generate_id(self, name: str) -> str:
        """Generate a slug-style domain ID from the name."""
        slug = name.lower().strip()
        slug = re.sub(r"[^a-z0-9]+", "-", slug)
        slug = re.sub(r"-+", "-", slug)
        slug = slug.strip("-")
        return slug or "unnamed-domain"

    def _generate_description(
        self, description: str, archetype_key: str,
    ) -> str:
        """Generate a formal domain description."""
        archetype_descs: dict[str, str] = {
            "legal": "Legal operations domain for contract analysis, compliance verification, and regulatory research.",
            "research": "Research domain for systematic investigation, data analysis, and knowledge publication.",
            "engineering": "Engineering domain for software development, deployment, and system reliability.",
            "finance": "Financial operations domain for analysis, risk management, and market research.",
            "healthcare": "Healthcare domain for patient care coordination, diagnosis support, and medical research.",
        }
        base = archetype_descs.get(archetype_key, "Custom domain for specialised task execution.")
        return f"{base} Source: {description}"

    def _generate_agents(
        self,
        description_lower: str,
        archetype_key: str,
        domain_id: str,
    ) -> list[AgentBlueprint]:
        """Generate agent blueprints based on archetype and description."""
        archetype = self._ARCHETYPES.get(archetype_key)
        if archetype is None:
            return self._default_agents(domain_id)

        agent_defs = archetype["agents"]
        if not isinstance(agent_defs, list):
            return self._default_agents(domain_id)

        agents: list[AgentBlueprint] = []
        for i, agent_def in enumerate(agent_defs):
            if not isinstance(agent_def, tuple) or len(agent_def) < 3:
                continue
            role, name, goal = agent_def[0], agent_def[1], agent_def[2]
            agent_id = f"{domain_id}-{role.value}-{i + 1}"
            agents.append(AgentBlueprint(
                agent_id=agent_id,
                name=name,
                role=role,
                goal=str(goal),
                backstory=f"{name} is a {role.value} agent in the {domain_id} domain. {goal}",
                capabilities=[role.value],
            ))

        return agents or self._default_agents(domain_id)

    def _default_agents(self, domain_id: str) -> list[AgentBlueprint]:
        """Generate default agents when no archetype matches."""
        return [
            AgentBlueprint(
                agent_id=f"{domain_id}-coordinator-1",
                name="Domain Coordinator",
                role=AgentRole.COORDINATOR,
                goal="Orchestrates tasks and coordinates other agents",
                backstory="Experienced coordinator who ensures smooth domain operations.",
                capabilities=["coordination", "task_assignment"],
            ),
            AgentBlueprint(
                agent_id=f"{domain_id}-executor-1",
                name="Task Executor",
                role=AgentRole.EXECUTOR,
                goal="Carries out assigned tasks efficiently",
                backstory="Reliable executor who handles task implementation.",
                capabilities=["execution", "task_completion"],
            ),
            AgentBlueprint(
                agent_id=f"{domain_id}-analyst-1",
                name="Domain Analyst",
                role=AgentRole.ANALYST,
                goal="Analyses domain data and produces actionable insights",
                backstory="Skilled analyst who turns data into decisions.",
                capabilities=["analysis", "reporting"],
            ),
            AgentBlueprint(
                agent_id=f"{domain_id}-reviewer-1",
                name="Quality Reviewer",
                role=AgentRole.REVIEWER,
                goal="Reviews outputs for quality and compliance",
                backstory="Thorough reviewer who ensures high standards.",
                capabilities=["review", "quality_assurance"],
            ),
        ]

    def _generate_skills(
        self,
        description_lower: str,
        archetype_key: str,
        domain_id: str,
        existing_skills: list[SkillDescriptor],
    ) -> list[SkillBlueprint]:
        """Generate skill blueprints, reusing existing skills where possible."""
        archetype = self._ARCHETYPES.get(archetype_key)
        if archetype is None:
            return self._default_skills(domain_id)

        skill_names = archetype["skills"]
        if not isinstance(skill_names, list):
            return self._default_skills(domain_id)

        existing_by_name: dict[str, SkillDescriptor] = {
            s.name.lower(): s for s in existing_skills
        }

        skills: list[SkillBlueprint] = []
        for skill_name in skill_names:
            existing = existing_by_name.get(skill_name.lower())
            if existing is not None:
                skills.append(SkillBlueprint(
                    skill_id=existing.skill_id,
                    name=existing.name,
                    description=existing.description,
                    version=existing.version,
                    is_reused=True,
                    source_domain=None,
                ))
            else:
                skill_id = f"{domain_id}-{skill_name.replace('_', '-')}"
                skills.append(SkillBlueprint(
                    skill_id=skill_id,
                    name=skill_name.replace("_", " ").title(),
                    description=f"{skill_name.replace('_', ' ')} capability for the {domain_id} domain",
                    is_reused=False,
                ))

        return skills or self._default_skills(domain_id)

    def _default_skills(self, domain_id: str) -> list[SkillBlueprint]:
        """Generate default skills when no archetype matches."""
        return [
            SkillBlueprint(
                skill_id=f"{domain_id}-task-management",
                name="Task Management",
                description="Core task management capability for the domain",
            ),
            SkillBlueprint(
                skill_id=f"{domain_id}-data-analysis",
                name="Data Analysis",
                description="Data analysis and reporting capability",
            ),
            SkillBlueprint(
                skill_id=f"{domain_id}-communication",
                name="Communication",
                description="Inter-agent and human communication capability",
            ),
        ]

    def _generate_workflows(
        self,
        description_lower: str,
        archetype_key: str,
        domain_id: str,
        agents: list[AgentBlueprint],
    ) -> list[WorkflowBlueprint]:
        """Generate workflow blueprints based on archetype and agents."""
        archetype = self._ARCHETYPES.get(archetype_key)
        workflow_defs: list[tuple[WorkflowType, str, str]] = []

        if archetype is not None:
            wf_list = archetype.get("workflows", [])
            if isinstance(wf_list, list):
                for wf in wf_list:
                    if isinstance(wf, tuple) and len(wf) >= 3:
                        workflow_defs.append(wf)

        if not workflow_defs:
            workflow_defs = [
                (WorkflowType.SEQUENTIAL, "Main Pipeline", "Gather -> Process -> Review -> Deliver"),
            ]

        agent_ids = [a.agent_id for a in agents]

        workflows: list[WorkflowBlueprint] = []
        for i, (wf_type, wf_name, wf_desc) in enumerate(workflow_defs):
            steps = [s.strip() for s in wf_desc.split("->")]
            workflows.append(WorkflowBlueprint(
                workflow_id=f"{domain_id}-workflow-{i + 1}",
                name=wf_name,
                workflow_type=wf_type,
                description=wf_desc,
                agent_ids=agent_ids[:min(len(agent_ids), 4)],
                steps=steps,
            ))

        return workflows

    def _generate_config(
        self,
        description_lower: str,
        archetype_key: str,
    ) -> DomainConfig:
        """Generate domain configuration based on archetype."""
        # High-risk domains require human approval
        high_risk_archetypes = {"legal", "healthcare", "finance"}
        requires_approval = archetype_key in high_risk_archetypes

        priority = "normal"
        if archetype_key in ("healthcare",):
            priority = "critical"
        elif archetype_key in ("finance", "legal"):
            priority = "high"

        return DomainConfig(
            max_agents=10,
            max_concurrent_tasks=5,
            requires_human_approval=requires_approval,
            data_retention_days=90,
            priority_level=priority,
        )


# ---------------------------------------------------------------------------
# BlueprintValidator — validates blueprints for safety and completeness
# ---------------------------------------------------------------------------


class BlueprintValidator:
    """Validates domain blueprints before they can be submitted as proposals.

    Checks for:
    - Completeness (minimum agents, skills, workflows)
    - Safety (no conflicting or dangerous configurations)
    - Uniqueness (no duplicate domain names or IDs)
    - Naming conventions (valid slugs, non-empty names)
    """

    MIN_AGENTS = 2
    MIN_SKILLS = 1
    MIN_WORKFLOWS = 1
    MAX_AGENTS = 20
    MAX_SKILLS = 30
    MAX_WORKFLOWS = 10

    def validate(
        self,
        blueprint: DomainBlueprint,
        existing_domains: list[DomainDescriptor],
    ) -> tuple[list[str], list[str]]:
        """Validate a domain blueprint.

        Args:
            blueprint: The blueprint to validate.
            existing_domains: Currently registered domains (for duplicate checks).

        Returns:
            A tuple of (errors, warnings). Errors prevent submission;
            warnings are informational.
        """
        errors: list[str] = []
        warnings: list[str] = []

        # -- Completeness checks --
        if not blueprint.domain_name.strip():
            errors.append("Domain name cannot be empty")

        if not blueprint.domain_id.strip():
            errors.append("Domain ID cannot be empty")

        if not blueprint.description.strip():
            warnings.append("Domain description is empty — consider adding a description")

        if len(blueprint.agents) < self.MIN_AGENTS:
            errors.append(
                f"Domain must have at least {self.MIN_AGENTS} agent(s), "
                f"got {len(blueprint.agents)}"
            )

        if len(blueprint.agents) > self.MAX_AGENTS:
            warnings.append(
                f"Domain has {len(blueprint.agents)} agents — consider reducing to "
                f"{self.MAX_AGENTS} or fewer for manageability"
            )

        if len(blueprint.skills) < self.MIN_SKILLS:
            errors.append(
                f"Domain must have at least {self.MIN_SKILLS} skill(s), "
                f"got {len(blueprint.skills)}"
            )

        if len(blueprint.workflows) < self.MIN_WORKFLOWS:
            errors.append(
                f"Domain must have at least {self.MIN_WORKFLOWS} workflow(s), "
                f"got {len(blueprint.workflows)}"
            )

        # -- Uniqueness checks --
        existing_names = {d.name.lower() for d in existing_domains}
        existing_ids = {d.domain_id.lower() for d in existing_domains}

        if blueprint.domain_name.lower() in existing_names:
            errors.append(
                f"Domain name '{blueprint.domain_name}' already exists"
            )

        if blueprint.domain_id.lower() in existing_ids:
            errors.append(
                f"Domain ID '{blueprint.domain_id}' already exists"
            )

        # -- Naming convention checks --
        if not re.match(r"^[a-z0-9][a-z0-9-]*[a-z0-9]$", blueprint.domain_id) and len(blueprint.domain_id) >= 2:
            errors.append(
                f"Domain ID '{blueprint.domain_id}' must be a lowercase "
                f"alphanumeric slug (e.g. 'legal-research')"
            )

        if len(blueprint.domain_name) > 100:
            warnings.append("Domain name is very long — consider shortening")

        # -- Agent checks --
        agent_ids = [a.agent_id for a in blueprint.agents]
        if len(agent_ids) != len(set(agent_ids)):
            errors.append("Duplicate agent IDs found in blueprint")

        for agent in blueprint.agents:
            if not agent.name.strip():
                errors.append(f"Agent {agent.agent_id} has an empty name")
            if not agent.goal.strip():
                warnings.append(f"Agent '{agent.name}' has no goal defined")

        # -- Skill checks --
        skill_ids = [s.skill_id for s in blueprint.skills]
        if len(skill_ids) != len(set(skill_ids)):
            errors.append("Duplicate skill IDs found in blueprint")

        # -- Workflow checks --
        for wf in blueprint.workflows:
            # Check that workflow agents exist in the blueprint
            missing = set(wf.agent_ids) - set(agent_ids)
            if missing:
                warnings.append(
                    f"Workflow '{wf.name}' references unknown agent(s): {missing}"
                )

        # -- Config checks --
        if blueprint.config.max_agents < len(blueprint.agents):
            warnings.append(
                f"Config max_agents ({blueprint.config.max_agents}) is less than "
                f"the number of agents in the blueprint ({len(blueprint.agents)})"
            )

        # -- Safety checks --
        if "hack" in blueprint.domain_id or "exploit" in blueprint.domain_id:
            errors.append("Domain ID contains potentially unsafe terms")

        return errors, warnings


# ---------------------------------------------------------------------------
# DomainCreationEngine — the main public API
# ---------------------------------------------------------------------------


class DomainCreationEngine:
    """One-Click Domain Creation engine for InkosAI.

    Generates complete domain blueprints from natural language descriptions,
    validates them for safety and completeness, and submits them through
    the Proposal approval workflow for human review.

    All operations are logged to the Tape for full auditability.

    Usage::

        engine = DomainCreationEngine(
            tape_service=tape_svc,
            introspector=introspector,
            proposal_engine=proposal_engine,
        )

        # Generate a blueprint (no side effects)
        blueprint = await engine.generate_domain_blueprint(
            description="Create a Legal Research Domain for contract analysis",
        )

        # Full creation pipeline (generates + validates + proposes)
        result = await engine.create_domain_from_description(
            description="Create a Legal Research Domain for contract analysis",
            created_by="human-001",
        )

        # After approval, register the domain
        domain = await engine.register_domain(blueprint.id)
    """

    def __init__(
        self,
        tape_service: TapeService,
        introspector: PrimeIntrospector | None = None,
        proposal_engine: ProposalEngine | None = None,
        domain_registry: DomainRegistry | None = None,
        blueprint_store: BlueprintStore | None = None,
        generator: BlueprintGenerator | None = None,
        validator: BlueprintValidator | None = None,
        folder_tree_service: FolderTreeService | None = None,
        aethergit: AdvancedAetherGit | None = None,
    ) -> None:
        self._tape = tape_service
        self._introspector = introspector
        self._proposal_engine = proposal_engine
        self._domain_registry = domain_registry or DomainRegistry()
        self._store = blueprint_store or BlueprintStore()
        self._generator = generator or BlueprintGenerator()
        self._validator = validator or BlueprintValidator()
        self._folder_tree_service = folder_tree_service
        self._aethergit = aethergit

    # ------------------------------------------------------------------
    # generate_domain_blueprint
    # ------------------------------------------------------------------

    async def generate_domain_blueprint(
        self,
        description: str,
        domain_name: str | None = None,
        creation_mode: CreationMode = CreationMode.HUMAN_GUIDED,
        created_by: str = "prime",
    ) -> DomainBlueprint:
        """Generate a domain blueprint from a natural language description.

        This is a read-only operation — it does not create any proposals
        or register any domains. It produces a blueprint that can be
        reviewed, modified, and then submitted.

        Args:
            description: Natural language description of the desired domain.
            domain_name: Optional explicit name; auto-generated if not provided.
            creation_mode: How the domain is being created.
            created_by: Who initiated the generation.

        Returns:
            A DomainBlueprint ready for validation and submission.

        Raises:
            ValueError: if the description is empty.
        """
        if not description.strip():
            raise ValueError("Domain description cannot be empty")

        # Get existing skills for potential reuse
        existing_skills: list[SkillDescriptor] = []
        if self._introspector is not None:
            existing_skills = self._introspector._skills.list_skills()

        # Generate the blueprint
        blueprint = self._generator.generate(
            description=description,
            domain_name=domain_name,
            creation_mode=creation_mode,
            existing_skills=existing_skills,
        )
        blueprint.created_by = created_by

        # Validate immediately so the user can see any issues
        existing_domains = self._domain_registry.list_domains()
        errors, warnings = self._validator.validate(blueprint, existing_domains)
        blueprint.validation_errors = errors
        blueprint.validation_warnings = warnings

        # Store the blueprint
        self._store.add(blueprint)

        # Log to Tape
        await self._tape.log_event(
            event_type="domain.blueprint_generated",
            payload={
                "blueprint_id": str(blueprint.id),
                "domain_name": blueprint.domain_name,
                "domain_id": blueprint.domain_id,
                "agent_count": len(blueprint.agents),
                "skill_count": len(blueprint.skills),
                "workflow_count": len(blueprint.workflows),
                "validation_errors": len(errors),
                "validation_warnings": len(warnings),
                "created_by": created_by,
            },
            agent_id="domain-creation-engine",
        )

        return blueprint

    # ------------------------------------------------------------------
    # create_domain_from_description
    # ------------------------------------------------------------------

    async def create_domain_from_description(
        self,
        description: str,
        domain_name: str | None = None,
        creation_mode: CreationMode = CreationMode.HUMAN_GUIDED,
        created_by: str = "prime",
    ) -> DomainCreationResult:
        """Full domain creation pipeline: generate, validate, propose.

        This generates a blueprint, validates it, and submits a Proposal
        for approval. The domain is NOT registered until the proposal is
        approved and ``register_domain()`` is called.

        Args:
            description: Natural language description of the desired domain.
            domain_name: Optional explicit name.
            creation_mode: How the domain is being created.
            created_by: Who initiated the creation.

        Returns:
            A DomainCreationResult with the blueprint and proposal info.

        Raises:
            BlueprintValidationError: if the blueprint has validation errors.
            ValueError: if the description is empty.
        """
        # Step 1: Generate blueprint
        blueprint = await self.generate_domain_blueprint(
            description=description,
            domain_name=domain_name,
            creation_mode=creation_mode,
            created_by=created_by,
        )

        # Step 2: Check for validation errors
        if blueprint.validation_errors:
            raise BlueprintValidationError(
                f"Blueprint has {len(blueprint.validation_errors)} validation error(s): "
                + "; ".join(blueprint.validation_errors)
            )

        # Step 3: Submit proposal
        proposal_id: UUID | None = None
        if self._proposal_engine is not None:
            # Determine risk level based on config
            risk = RiskLevel.LOW
            if blueprint.config.priority_level in ("high", "critical"):
                risk = RiskLevel.MEDIUM
            if blueprint.config.requires_human_approval:
                risk = RiskLevel.MEDIUM
            if blueprint.config.priority_level == "critical":
                risk = RiskLevel.HIGH

            # Build implementation steps
            impl_steps = [
                f"Register domain '{blueprint.domain_name}' with ID '{blueprint.domain_id}'",
                f"Create {len(blueprint.agents)} agent(s): "
                + ", ".join(a.name for a in blueprint.agents),
                f"Set up {len(blueprint.skills)} skill(s): "
                + ", ".join(s.name for s in blueprint.skills),
                f"Configure {len(blueprint.workflows)} workflow(s): "
                + ", ".join(w.name for w in blueprint.workflows),
                "Apply domain configuration and constraints",
            ]

            proposal = await self._proposal_engine.propose(
                title=f"Create Domain: {blueprint.domain_name}",
                modification_type=ModificationType.DOMAIN_CREATION,
                description=f"Create the '{blueprint.domain_name}' domain: {blueprint.description}",
                reasoning=f"Domain creation requested by {created_by} based on description: {blueprint.source_description}",
                expected_impact=f"Adds a new '{blueprint.domain_name}' domain with "
                f"{len(blueprint.agents)} agents, {len(blueprint.skills)} skills, "
                f"and {len(blueprint.workflows)} workflows.",
                risk_level=risk,
                implementation_steps=impl_steps,
                proposed_by=created_by,
            )
            proposal_id = proposal.id
            blueprint.proposal_id = proposal.id
            blueprint.status = DomainStatus.PROPOSED
            self._store.update(blueprint)

        # Step 4: Log creation event
        await self._tape.log_event(
            event_type="domain.creation_requested",
            payload={
                "blueprint_id": str(blueprint.id),
                "domain_name": blueprint.domain_name,
                "domain_id": blueprint.domain_id,
                "proposal_id": str(proposal_id) if proposal_id else None,
                "created_by": created_by,
                "creation_mode": creation_mode.value,
            },
            agent_id="domain-creation-engine",
        )

        return DomainCreationResult(
            blueprint=blueprint,
            proposal_id=proposal_id,
            registered=False,
            message="Domain blueprint generated and proposal submitted. "
            "Awaiting human approval before registration.",
        )

    # ------------------------------------------------------------------
    # register_domain
    # ------------------------------------------------------------------

    async def register_domain(
        self,
        blueprint_id: UUID,
        reviewer: str | None = None,
    ) -> DomainDescriptor:
        """Register a domain after its proposal has been approved.

        This is the final step — it creates the domain in the registry
        and registers all agents and skills.

        Args:
            blueprint_id: The UUID of the blueprint to register.
            reviewer: The human who approved the proposal.

        Returns:
            The registered DomainDescriptor.

        Raises:
            BlueprintNotFoundError: if the blueprint does not exist.
            DomainNotApprovedError: if the associated proposal is not approved.
            DuplicateDomainError: if the domain already exists.
        """
        blueprint = self._store.get(blueprint_id)
        if blueprint is None:
            raise BlueprintNotFoundError(
                f"Blueprint {blueprint_id} not found"
            )

        # Check proposal status if a proposal was created
        if blueprint.proposal_id is not None and self._proposal_engine is not None:
            proposal = self._proposal_engine._store.get(blueprint.proposal_id)
            if proposal is None or proposal.status not in (
                ProposalStatus.APPROVED, ProposalStatus.IMPLEMENTED,
            ):
                raise DomainNotApprovedError(
                    f"Domain '{blueprint.domain_name}' cannot be registered — "
                    f"proposal {blueprint.proposal_id} is not approved "
                    f"(status: {proposal.status.value if proposal else 'unknown'})"
                )

        # Check for duplicate domain
        existing = self._domain_registry.get_domain(blueprint.domain_id)
        if existing is not None:
            raise DuplicateDomainError(
                f"Domain with ID '{blueprint.domain_id}' already exists"
            )

        # Register the domain
        domain = DomainDescriptor(
            domain_id=blueprint.domain_id,
            name=blueprint.domain_name,
            description=blueprint.description,
            agent_count=len(blueprint.agents),
        )
        self._domain_registry.register(domain)

        # Generate the folder tree (canonical source of truth)
        # Folder tree is an enhancement — don't fail registration on error.
        tree = None
        if self._folder_tree_service is not None:
            with contextlib.suppress(Exception):
                tree = await self._folder_tree_service.create_tree(
                    domain_id=blueprint.domain_id,
                    domain_name=blueprint.domain_name,
                    description=blueprint.description,
                    agents=blueprint.agents,
                    skills=blueprint.skills,
                    workflows=blueprint.workflows,
                    config=blueprint.config,
                )

        # Folder Thinking Mode — Prime validates the generated tree structure
        if tree is not None and self._introspector is not None:
            with contextlib.suppress(Exception):
                await self._introspector.folder_navigate(blueprint.domain_id, "")

        # Commit the folder tree to AetherGit for version control
        if tree is not None and self._aethergit is not None:
            with contextlib.suppress(Exception):
                commit = AetherCommit(
                    author="domain-creation-engine",
                    message=f"Create domain: {blueprint.domain_name}",
                    commit_type="domain_creation",
                    scope=blueprint.domain_id,
                    performance_metrics={
                        "agent_count": len(blueprint.agents),
                        "skill_count": len(blueprint.skills),
                        "workflow_count": len(blueprint.workflows),
                        "node_count": len(tree.nodes),
                    },
                    confidence_score=1.0,
                    proposed_by=reviewer or blueprint.created_by,
                    evolution_approved=True,
                )
                self._aethergit.add_commit(commit, branch=f"domain/{blueprint.domain_id}")

        # Register agents in the introspector's agent registry
        if self._introspector is not None:
            for agent_bp in blueprint.agents:
                self._introspector._agents.register(AgentDescriptor(
                    agent_id=agent_bp.agent_id,
                    name=agent_bp.name,
                    capabilities=agent_bp.capabilities,
                    status="idle",
                ))

        # Register new skills in the introspector's skill registry
        if self._introspector is not None:
            for skill_bp in blueprint.skills:
                if not skill_bp.is_reused:
                    self._introspector._skills.register(SkillDescriptor(
                        skill_id=skill_bp.skill_id,
                        name=skill_bp.name,
                        version=skill_bp.version,
                        description=skill_bp.description,
                    ))

        # Update blueprint status
        blueprint.status = DomainStatus.ACTIVE
        with contextlib.suppress(BlueprintNotFoundError):
            self._store.update(blueprint)

        # Mark proposal as implemented
        if blueprint.proposal_id is not None and self._proposal_engine is not None:
            with contextlib.suppress(Exception):
                await self._proposal_engine.mark_implemented(blueprint.proposal_id)

        # Log to Tape
        await self._tape.log_event(
            event_type="domain.registered",
            payload={
                "blueprint_id": str(blueprint.id),
                "domain_id": blueprint.domain_id,
                "domain_name": blueprint.domain_name,
                "agent_count": len(blueprint.agents),
                "skill_count": len(blueprint.skills),
                "workflow_count": len(blueprint.workflows),
                "reviewer": reviewer,
            },
            agent_id="domain-creation-engine",
        )

        return domain

    # ------------------------------------------------------------------
    # validate_blueprint
    # ------------------------------------------------------------------

    def validate_blueprint(
        self,
        blueprint: DomainBlueprint,
    ) -> tuple[list[str], list[str]]:
        """Validate a blueprint without storing or submitting it.

        Args:
            blueprint: The blueprint to validate.

        Returns:
            A tuple of (errors, warnings).
        """
        existing_domains = self._domain_registry.list_domains()
        return self._validator.validate(blueprint, existing_domains)

    # ------------------------------------------------------------------
    # Query methods
    # ------------------------------------------------------------------

    async def list_domains(self) -> list[DomainDescriptor]:
        """List all registered domains."""
        return self._domain_registry.list_domains()

    async def get_domain(self, domain_id: str) -> DomainDescriptor | None:
        """Retrieve a single domain by ID."""
        return self._domain_registry.get_domain(domain_id)

    async def get_blueprint(self, blueprint_id: UUID) -> DomainBlueprint:
        """Retrieve a stored blueprint by ID.

        Raises:
            BlueprintNotFoundError: if the blueprint does not exist.
        """
        bp = self._store.get(blueprint_id)
        if bp is None:
            raise BlueprintNotFoundError(
                f"Blueprint {blueprint_id} not found"
            )
        return bp

    async def list_blueprints(self) -> list[DomainBlueprint]:
        """List all stored blueprints."""
        return self._store.list_all()

    async def delete_blueprint(self, blueprint_id: UUID) -> None:
        """Delete a stored blueprint.

        Raises:
            BlueprintNotFoundError: if the blueprint does not exist.
        """
        bp = self._store.get(blueprint_id)
        if bp is None:
            raise BlueprintNotFoundError(
                f"Blueprint {blueprint_id} not found"
            )
        if bp.status == DomainStatus.ACTIVE:
            raise DomainCreationError(
                f"Cannot delete blueprint for active domain '{bp.domain_name}'"
            )
        self._store.remove(blueprint_id)
